# Site settings
author: Jackson Morgan
title: Jackson
header-img: img/home-bg.png
email: jacksonmo@me.com
copyright_name: Jackson Morgan
description: > # this means to ignore newlines until "baseurl:"
  Software
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ohjacksn

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
